---
- name: Create Network Backup Play
  hosts: all
  gather_facts: false
  tasks:
    # - name: Create timestamp for backup if backup_file_name is not provided
    #   ansible.builtin.set_fact:
    #     datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"
    #   when: backup_file_name is not defined

    # - name: Set backup file name
    #   ansible.builtin.set_fact:
    #     backup_file_name_final: "{{ backup_file_name | default(datetime) }}"

    - name: Create Network Backup and Push to SCM
      ansible.builtin.include_role:
        name: network.backup.backup
      vars:
        operation: backup
        data_store:
          scm:
            origin:
              url: "https://github.com/rohitthakur2590/network_automation_demo"  # Set by survey
              token: "{{ token }}"  # Set by survey
              user:
                name: "rohitthakur2590"  # Set by survey
                email: "rohitthakur2590@outlook.com"  # Set by survey
          backup_file_name: "demo_backup"  # Use conditional name
