---
- name: Perform health checks
  hosts: all
  gather_facts: false
  tasks:
  - name: Health hecks
    ansible.builtin.include_role:
      name: network.interfaces.health_checks
    vars:
      ansible_network_os: cisco.ios.ios
      interfaces_health_check:
        name: health_check
        vars:
          details: True
          checks:
            - name: all_admin_state_down
            # - name: min_operational_state_up
            #   min_count: 1
            # - name: all_admin_state_up
            # - name: min_admin_state_up
            #   min_count: 1
