---
- name: Perform health checks
  hosts: all
  gather_facts: true
  tasks:
  - name: Health checks
    register: health_results
    ansible.builtin.include_role:
      name: network.interfaces.health_checks
    vars:
      ansible_network_os: cisco.ios.ios
      interfaces_health_check:
        name: health_check
        vars:
          details: True
          checks:
            - name: all_admin_state_up
            - name: all_operational_state_up


  - name: Display health results
    ansible.builtin.debug:
      msg: "{{ health_results }}"
      
