---
- name: Perform health checks
  hosts: all
  gather_facts: false
  tasks:
  - name: Health hecks
    ansible.builtin.include_role:
      name: network.bgp.health_checks
    vars:
      bgp_health_check:
        name: health_check
        vars:
          details: True
          checks:
            - name: all_neighbors_up
            - name: min_neighbors_up
              min_count: 1
            - name: bgp_status_summary
