---
- hosts: all
  gather_facts: true
  tasks:
    - block: 
      - name: Network Resource Manager
        ansible.builtin.include_role:
          name: network.base.remediate
        vars:
          resources:
            - 'interfaces'
            - 'l2_interfaces'
            - 'l3_interfaces'
            - 'bgp_global'
            - 'bgp_address_family'
            - 'ospfv2'
            - 'ospfv3'
            - 'ospf_interfaces'
            - 'bgp_global'
            - 'bgp_global'
          data_store:
            scm:
              parent_directory: "/home/rhel"
              origin:
                url: https://github.com/rohitthakur2590/network_automation_demo.git
                token: "{{ token }}"
                user:
                  name: rohitthakur2590
