---
- name: Restore Play
  hosts: all
  gather_facts: false
  collections:
    - cisco.ios
  tasks:
    - name: The network restore task
      ansible.builtin.include_role:
        name: network.backup.restore
      vars:
        operation: restore
        data_store:
          scm:
            origin:
              url: "https://github.com/rohitthakur2590/network_automation_demo"
              token: "{{ token }}"
              path: "demo_backup.txt"
